apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
stringData:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secret.MONGO_INITDB_ROOT_PASSWORD }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secret.MONGO_INITDB_ROOT_USERNAME }}
