version: "3.7"

networks:
  backend:

services:
  PrivateNote:
    container_name: "PrivateNote"
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    env_file:
      - .env

    image: "private-note"
    networks:
      - backend


  mongodb:
    image: mongo
    container_name: "mongodb"
    hostname: mongodb
    ports:
      - "27018:27017"
#    environment:
#     - MONGO_INITDB_ROOT_USERNAME=admin1
#     - MONGO_INITDB_ROOT_PASSWORD=admin1
#     - MONGO_INITDB_DATABASE=private_notes
    networks:
      - backend
