apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: default
data:
  EXPIRE_TIME: "18000"
  MONGO_HOST: "mongodb"
  MONGO_INITDB_DATABASE: "private_notes"
  MONGO_PORT: "27017"