apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-deployment
  template:
    metadata:
      labels:
        app: mongodb-deployment
    spec:
      containers:
      - name: mongodb-deployment
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
        envFrom:
          - configMapRef:
              name: mongodb-config
          - secretRef:
              name: mongodb-secret
        volumeMounts:
          - name: mongodb-persistent-storage
            mountPath: /data/db

      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
            claimName: mongodb-pvc



