apiVersion: v1
kind: Service
metadata:
  name: mongodb-stateful-service
  labels:
    name: mongodb-stateful-service
spec:
  selector:
    role: mongo
  ports:
    - protocol: TCP
      port: 27017
  clusterIP: None

